language: node_js
# Test on a selection of operating systems
os:
  - linux
  - osx
  - windows
# Build with both the latest and latest long-term-support by default
node_js:
  - node
  - lts/*
# Cache the modules we build against.
cache: npm
# Build by running the tests (this is the Travis default)
script: npm test
